package com.example.ui

import kotlinx.serialization.Serializable

internal val staticPharmacies = listOf(
    VerifiedPharmacy("Ayom Pharmacy", "0803 374 1361", "16 Adewunmi Adu Street, Off Jibowu Road, U-Turn Bus stop", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("DrugMaster Pharmacy", "0708 937 3692", "1 Prince Adesua Street, Abule Egba", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("Fiasmad Pharmacy", "0803 325 5444", "98 Agbe Road, U-Turn Bus stop", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("Health Save Pharmacy", "0810 276 8363", "5 Baba Egba Street, Ile Iwe Bus Stop, Meran, Lagos", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("Josfekmart Pharmacy & Store", "0802 491 9520", "146 Ekoro Road, Ekoro Junction, Abule Egba", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("Jubilant Pharmacy", "0805 513 2851", "Ahmadiyya Bus stop, Lagos-Abeokuta Expressway", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("KallyCare Pharmacy", "0806 631 2098", "116/118 Ekoro Road, Abule Egba", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("Nikub Triumph Pharmacy", "0802 526 7678", "Ahmed Mohammed Way, Abule Egba, Lagos", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("Ramsgate Pharmacy", "0807 089 2803", "Beside Uptown Hospital, Ijaiye Bus stop, Lagos-Abeokuta Expressway", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("Tito B. Pharmacy", "0807 928 7553", "53 Charity Road, New Oko Oba, Abule Egba", "Independent Retailer", "Lagos", "Abule Egba"),
    VerifiedPharmacy("Drugrite Pharmacy", "0805 674 8647", "3 Agbado Station Road, Ijaiye Bus stop, Agbado", "Independent Retailer", "Lagos", "Agbado"),
    VerifiedPharmacy("Abek Pharmacy", "0808 430 0136", "143 Ipaja Road, Agbotikuyo Bus stop, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Atidam Pharmacy", "0803 337 8445", "1 Olayiwola Street, Charity Road, Oko Oba, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Beginning & End Pharmacy", "0805 937 9672", "1 Church Street by Elere Police Station, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Ca & Jo Pharmacy", "0803 437 3075", "1 Alfa-Nla Road, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Cimis Pharmacy", "0803 778 4608", "32 Adealu Street, Adealu, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Drug for All Pharmacy", "0803 505 8640", "70 Amoo Street, Orile-Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Ebechi Pharmacy", "0812 566 1819", "21 Balogun Street, Pen-Cinema, Moshalashi, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Hycax Pharmacy", "0806 345 7903", "37 Alfa-Nla Street, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Ify Peters Pharmacy", "0806 982 4993", "224 Old Ipaja Road, Mulero Bus-stop, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Jaybion Pharmacy", "0802 322 9843", "Suite A, Bola Tinubu Shopping Complex, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Kanymed Pharmacy", "0905 691 0133", "1 Oko Oba Road, Banko Plaza, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Letonia Pharmacy", "0803 392 2445", "65 Alfa-Nla Street, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Makbi Pharmacy", "0816 501 8825 / 0703 022 2035", "2 Jaiye Olowu Street, Opp Swipha, Dopemu, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Metro Plus Pharmacy", "0703 890 2557", "24 Ogunnaike Street, Adealu, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Monmak Global Resources", "0812 554 4135", "2 Ayige Street, Orile Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Mooveon Pharmacy", "No phone", "30 Iju Road, Pen Cinema, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("OTS Pharmacy", "0812 554 4135", "2 Ayige Street, Orile Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Pambonac Pharmacy", "0818 182 5176", "112 Old Abeokuta Road, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Petmaur Pharmacy", "0905 191 9024", "Block A, Suite 4, Bola Tinubu Shopping Complex, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Prognosy Pharmacy", "0909 864 1641", "359 Old Agege Motor Road, Oko Oba, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Prophilax Pharmacy", "0703 122 1056", "148 Off Oniwaya Road, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Ransomed Pharmacy", "0803 669 1177", "1 Babs Ogunwole Street, Oko Oba, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Samtex Pharmacy", "0803 722 3000", "24 Ayige Road, Funmilayo Street, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Skills Global Care Pharmacy", "0708 463 7410", "2A Shitta Street, Dopemu, Agege", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Tanbimex Pharmacy", "0813 317 8697", "15 Okeho Street, Pako Bus-stop, Dopemu", "Independent Retailer", "Lagos", "Agege"),
    VerifiedPharmacy("Tymed Pharmacy (Online Pharmacy)", "+234 701 953 4153", "10 E. Mac Yoroki Street, Agungi East Estate", "Independent Retailer", "Lagos", "Agungi"),
    VerifiedPharmacy("Billhills Healthcare & Pharmacy", "0904 026 4298", "Ojaja Mall, Abraham Adesanya, Ogombo Road, Ajah", "Independent Retailer", "Lagos", "Ajah"),
    VerifiedPharmacy("Blessed Hossanah Pharmacy", "0802 930 5923", "Shop 29 NEPA Road, Ajah", "Independent Retailer", "Lagos", "Ajah"),
    VerifiedPharmacy("Drug Matter Pharmacy", "0802 313 0814", "Ado Road, Ajah", "Independent Retailer", "Lagos", "Ajah"),
    VerifiedPharmacy("Elfimo Pharmacy & Stores (Ikota)", "0812 908 3071", "Shop H-94 Ikota Shopping Complex, Ajah", "Independent Retailer", "Lagos", "Ajah"),
    VerifiedPharmacy("MedExpress Pharmacy", "0803 300 1059", "7 Adewale Kolawole Crescent off T.F Kuboye Street, Ajah", "Independent Retailer", "Lagos", "Ajah"),
    VerifiedPharmacy("Primeah Pharmacy", "No phone", "17/18 Lekki Epe Expressway, Oko Ado, Ajah", "Independent Retailer", "Lagos", "Ajah"),
    VerifiedPharmacy("R-Kay Pharmacy", "No phone", "Ajah", "Independent Retailer", "Lagos", "Ajah"),
    VerifiedPharmacy("Guardalife Pharmacy", "No phone", "No 8 Ajibade Babatola Street, Ajao Estate", "Independent Retailer", "Lagos", "Ajao Estate"),
    VerifiedPharmacy("Mednet Pharmacy", "0907 313 9870", "50 Fatai Irawo Street", "Independent Retailer", "Lagos", "Ajao Estate"),
    VerifiedPharmacy("Primus Pharmacy", "+234 816 617 7733", "14 Awoniyi Elemo St", "Independent Retailer", "Lagos", "Ajao Estate"),
    VerifiedPharmacy("Prodrug Pharmacy (Ajao)", "0803 450 0599", "7B Asa Afariogun Street, Ajao Estate", "Independent Retailer", "Lagos", "Ajao Estate"),
    VerifiedPharmacy("Alpharma Pharmacy Store", "0803 333 9137", "23 St. Finbarr Road, Chief Bright Oridami Street", "Independent Retailer", "Lagos", "Akoka"),
    VerifiedPharmacy("Beulah Pharmaceutical Chemists Ltd", "0802 306 4112, 0803 641 1416", "Beulah Plaza, 14 St. Finbarr's College Road", "Independent Wholesaler", "Lagos", "Akoka"),
    VerifiedPharmacy("Drugs Cafe Pharmacy & Mini Mart", "0903 514 3562", "62 St. Finbarr's College Road", "Independent Retailer", "Lagos", "Akoka"),
    VerifiedPharmacy("Eagle Pharmacy", "No phone", "45 Shasha Road, Akowonjo", "Independent Retailer", "Lagos", "Akowonjo"),
    VerifiedPharmacy("Jullifem Healthcare", "0813 386 5638", "1 Adeyemi Street, Alagbado", "Independent Retailer", "Lagos", "Alagbado"),
    VerifiedPharmacy("Justinak Pharmacy", "0816 650 8792", "1/2 AIT Road, Kola Bus-stop, Alagbado", "Independent Retailer", "Lagos", "Alagbado"),
    VerifiedPharmacy("League Pharmacy Limited", "0801 343 8888, 0818 266 1500", "289 Herbert Macaulay Way", "Independent Retailer", "Lagos", "Alagomeji, Yaba"),
    VerifiedPharmacy("Folyma Pharmacy", "0803 365 1566", "Alakuko Road, Alakuko", "Independent Retailer", "Lagos", "Alakuko"),
    VerifiedPharmacy("Glory Divine Pharmacy", "0803 670 6553", "1 Bale Animashaun Road, Alakuko Bus stop", "Independent Retailer", "Lagos", "Alakuko"),
    VerifiedPharmacy("Palchris Pharmacy", "No phone", "9 Egbado Street, Off Dalemo Bus stop, Alakuko", "Independent Retailer", "Lagos", "Alakuko"),
    VerifiedPharmacy("Supavice Pharmacy & Stores", "+234 813 811 2519", "13 Baale Animashaun Rd", "Independent Retailer", "Lagos", "Alakuko"),
    VerifiedPharmacy("Vigilis Pharmacy", "0805 413 1742", "45 Nureni Yusuf Shopping Complex, Alakuko", "Independent Retailer", "Lagos", "Alakuko"),
    VerifiedPharmacy("Elna Pharmacy & Stores", "0813 799 1267", "33 Ijegun Road, Ikotun", "Independent Retailer", "Lagos", "Alimosho"),
    VerifiedPharmacy("Engraced Pharmacy", "0802 757 3761, 0803 822 1372, 0812 796 6963", "80 Egbeda-Idimu Road, Egbeda", "Independent Retailer", "Lagos", "Alimosho"),
    VerifiedPharmacy("Goscel Pharmacy", "No phone", "30B Ayo Afolabi Street, Aboru, Iyana-Ipaja", "Independent Retailer", "Lagos", "Alimosho"),
    VerifiedPharmacy("Health Consult Pharmacy", "No phone", "12 Odunsi Road, opposite Everlead College, Ogunseye Ikola", "Independent Retailer", "Lagos", "Alimosho"),
    VerifiedPharmacy("Jodag Pharmacy", "No phone", "Block 61, Plot 1456, Leye Adebowale Street, Heritage Estate, Aboru, Alimosho", "Independent Retailer", "Lagos", "Alimosho"),
    VerifiedPharmacy("Lifepoint Pharmacy", "0818 255 6242", "20/26 Alaba Oro Road, Amukoko", "Independent Retailer", "Lagos", "Amukoko"),
    VerifiedPharmacy("Cus Pharmacy", "0802 429 6039", "56 Old Ojo Road, Amuwo", "Independent Retailer", "Lagos", "Amuwo-Odofin"),
    VerifiedPharmacy("Grace Johnson Pharmacy", "0816 268 2266", "434 Old Ojo Road, Abule Ado", "Independent Retailer", "Lagos", "Amuwo-Odofin"),
    VerifiedPharmacy("Live More Pharmacy", "0808 605 8265", "210 Old Ojo Road, Agboju", "Independent Retailer", "Lagos", "Amuwo-Odofin"),
    VerifiedPharmacy("Mackebe Pharmacy", "0803 057 3611, 0808 815 5554", "1C Marwa Road, Satellite Town", "Independent Retailer", "Lagos", "Amuwo-Odofin"),
    VerifiedPharmacy("Med Store Pharmacy", "0806 578 2292", "133 Old Ojo Road, Agboju", "Independent Retailer", "Lagos", "Amuwo-Odofin"),
    VerifiedPharmacy("Seadone Pharmacy", "0808 523 4436", "230 Old Ojo Road, Mazamaza", "Independent Retailer", "Lagos", "Amuwo-Odofin"),
    VerifiedPharmacy("Vine Pharmacy & Stores", "No phone", "Amuwo-Odofin (public listing)", "Independent Retailer", "Lagos", "Amuwo-Odofin"),
    VerifiedPharmacy("RDC Pharmacy", "0815 613 6683", "7/8 Bush Street, Anthony, Lagos", "Independent Retailer", "Lagos", "Anthony"),
    VerifiedPharmacy("Eno Pharmacy", "01 497 7200", "Adebayo Mokuolu Street", "Independent Retailer", "Lagos", "Anthony Village"),
    VerifiedPharmacy("Medlink Pharmacy & Supermarket", "+234 818 039 4308", "15 Sunmola Street", "Independent Retailer", "Lagos", "Anthony, Maryland"),
    VerifiedPharmacy("Remedia Pharmacy", "0802 784 4181, 0812 873 1567", "69 Kofo Abayomi Avenue", "Independent Retailer", "Lagos", "Apapa"),
    VerifiedPharmacy("Bisgan Pharmacy", "0706 438 8776", "5 Unity Street, Ayobo", "Independent Retailer", "Lagos", "Ayobo"),
    VerifiedPharmacy("De-Omega Pharmacy", "0908 616 6392", "151 Ipaja Ayobo Road, Igbogbo Gbagada Bus stop, Ayobo", "Independent Retailer", "Lagos", "Ayobo"),
    VerifiedPharmacy("Favalin Pharmacy", "0807 412 0389", "27 Unity Street, Ayobo", "Independent Retailer", "Lagos", "Ayobo"),
    VerifiedPharmacy("Jenjil Pharmacy", "0802 344 1885", "118 Asipa Road, Ayobo", "Independent Retailer", "Lagos", "Ayobo"),
    VerifiedPharmacy("Karadin Pharmacy", "0805 431 2909", "162 Lord Reign Plaza, Ayobo", "Independent Retailer", "Lagos", "Ayobo"),
    VerifiedPharmacy("FlintY Rock Pharmacy", "No phone", "13 Isashi Road, Mebamu, Badagry", "Independent Retailer", "Lagos", "Badagry"),
    VerifiedPharmacy("J.O. Sarchmore Pharmacy", "0703 341 2636", "118 Old Lagos Road, Ajara Dackor, Badagry", "Independent Retailer", "Lagos", "Badagry"),
    VerifiedPharmacy("M.o.c Hossana Pharmacy", "0805 477 1791", "Ibereko, Badagry", "Independent Retailer", "Lagos", "Badagry"),
    VerifiedPharmacy("Yankee Pharmacy", "0703 701 2498", "75 Hospital Road, Ajara, Badagry", "Independent Retailer", "Lagos", "Badagry"),
    VerifiedPharmacy("C. Prime Pharmacy", "0701 260 6864", "52 Okuta Street, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("CPG Pharmacy", "0803 572 4576", "37 Tijani Ashogbon Street, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Cyronx Pharmacy", "0803 043 2917", "41 Ilaje Road, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Foundation Pharmacy", "0818 175 9215", "23 Emmanuel Street, off First Bank, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Franco Pharmacy", "0803 412 7564", "49 Okuta Road, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Grasol Pharmacy & Store", "0802 312 3759", "71 Igiolugbin Street, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Jomason Pharmacy", "0903 743 5933", "24 Okuta Street, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Lifeplus Pharmacy (Bariga)", "0814 150 1109", "29 Gbagada Road, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Nich Pharmacy", "0902 008 0902", "38 Okuta Road, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Olivegreen Pharmacy", "No phone", "33 Okuta Road, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Pinco Pharmacy & Store (Bariga)", "0802 344 4408", "111 Igi-Olugbin Street, Pedro, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Rinzco Pharmacy", "0814 434 9779", "32 Okuta Street, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Surplus Pharmacy", "0803 352 3345", "48 Igi Olugbin Street, Ladi-Lak, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Ugoldenchuks Pharmacy", "0706 120 4155", "42 Jagunmola Road, Opp. Oando Filling Station, Bariga", "Independent Retailer", "Lagos", "Bariga"),
    VerifiedPharmacy("Kunimed PharmaChem Limited", "0803 404 0907, 0803 560 7172", "1 Adelanwa Street", "Independent Retailer", "Lagos", "Dopemu"),
    VerifiedPharmacy("Hope-cee Pharmacy & Stores", "0803 715 4747, 0809 872 9999", "6 Thomas Street", "Independent Retailer", "Lagos", "Ebute Metta West"),
    VerifiedPharmacy("Life Back Pharmacy", "0817 119 075", "Ebute-Metta, Lagos", "Independent Retailer", "Lagos", "Ebute-Metta"),
    VerifiedPharmacy("Pharmaflash Pharmacy", "0802 314 0347", "38 Cemetery Street, Ebute-Metta", "Independent Retailer", "Lagos", "Ebute-Metta"),
    VerifiedPharmacy("Pius & Gina Pharmacy (Ebute-Metta)", "No phone", "28 Glover Street, Opposite Old Yaba Road, Ebute-Metta", "Independent Retailer", "Lagos", "Ebute-Metta"),
    VerifiedPharmacy("Tonyson Pharmacy & Stores", "01 295 2044, 0708 557 0677, 0802 303 9766", "47A Simpson Street", "Independent Retailer", "Lagos", "Ebute-Metta"),
    VerifiedPharmacy("Ambassadors Pharmacy", "0805 347 6912", "19 Isiba Oluwo Street, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Charther Pharmacy", "No phone", "250 Akowonjo Road, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Clich Pharmacy", "0803 322 4562", "3/5 Godlove, Akowonjo Road, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Crystal Specialist Hospital Pharmacy", "+234 1 473 5162", "148-150 Akowonjo Road, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Kerion Pharmacy", "0817 777 8913", "Gowon Estate, 3rd Avenue, opposite St. Bernadette School, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Lola Pharmacy", "0803 347 0652", "10 Idimu Road, Egbeda Bus stop", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Nard Pharmacy (Alimosho)", "0915 430 6656", "3 Egbeda-Idimu Road, Divine Court Plaza, Alimosho Bus stop, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Nectarite Pharmacy", "No phone", "No. 2 Olorunwa Close, Karimu Laka Street, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Nuges Pharmacy", "No phone", "26/27 Karimu Laka Street by Oba's Palace, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Ofred Pharmacy", "No phone", "Adenle Road, Off 431 Junction, Gowon Estate, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Pharmatone Pharmacy", "No phone", "136 Egbeda-Idimu Road, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Pius & Gina Pharmacy (Egbeda)", "No phone", "107A Akowonjo Road, Vulcanizer Bus-stop, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Primelead Pharmacy", "No phone", "H27 A Close, Road 34, Opposite Navy Block 86, Gowon Estate, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Salvich Pharmacy", "No phone", "9 Lawal Street, Vulcanizer Bus stop, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Teaco Pharmacy", "0813 526 2542", "50 Akowonjo Road, Egbeda", "Independent Retailer", "Lagos", "Egbeda"),
    VerifiedPharmacy("Blessed Neodyke Pharmacy", "0803 406 0316", "21 Fadu Avenue, Ejigbo", "Independent Retailer", "Lagos", "Ejigbo"),
    VerifiedPharmacy("Gbajumo Ventures", "0802 412 7633", "8 Ifoshi Street, Ejigbo", "Independent Retailer", "Lagos", "Ejigbo"),
    VerifiedPharmacy("Kings Patent Medicine Store", "0080 341 4609", "1 Olusoga Street, Ejigbo", "Independent Retailer", "Lagos", "Ejigbo"),
    VerifiedPharmacy("Sabuzo Mega Pharmacy", "0817 921 4868", "3 Ojuola Street, Ejigbo", "Independent Retailer", "Lagos", "Ejigbo"),
    VerifiedPharmacy("Adornlife Pharmacy", "0802 312 5693", "Shop C11/005, A Close, 22 Road, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Drugplus Pharmacy", "0802 344 0217", "32/41 Road Junction, 32 Road, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Kaycee Pharmacy (Festac 2)", "0803 670 8884", "22 Road, Off 5th Avenue, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Kaycee Pharmacy (Festac)", "0809 531 2332", "22 Road, Festac Town", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Kris Daniel Pharmacy", "0803 303 2903", "Opposite Mr Biggs, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Kris Daniels Pharmacy (Festac)", "0803 244 1992", "1st Avenue, Opposite Mr. Biggs, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Monis Natural Healthcare", "0802 360 0428", "5th Avenue, By Last Bus stop, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Osbud Pharmacy", "0809 500 0005", "5th Avenue, E/G Close, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Ox Pharm", "0808 388 1907", "32 Road, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Victorious Pharmacy", "No phone", "31 Road, Opposite D Close, Festac", "Independent Retailer", "Lagos", "Festac"),
    VerifiedPharmacy("Ajekins Pharmacy", "0803 501 8100", "11A Ibrahim Onashokun Street, Ifako, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Come Alive Pharmacy", "0803 073 2692", "15 Akerele Annex Church Street, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Familycare Pharmacy", "0809 430 8361", "89 Oworo Road, Oworoshoki", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("HMR Pharmacy", "0809 991 0978", "38 Lanne Awolokun Street, Gbagada Phase 2, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Isalu Pharmacy", "0803 654 4255", "55 Diya Street, Near Deeper Life Church, Ifako, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Kerson Pharmacy", "0803 254 0109", "2 Williams Street, Sawmill, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Lifeplus Pharmacy (Gbagada)", "0802 930 3367", "29 Gbagada Road, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Lolana Pharmacy", "0808 080 8827", "2 Diya Street, Tantalizer Building, Ifako", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Mebik Pharmacy", "0803 402 7579", "19b Church Street, Opp. Gbagada General Hospital", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Medmark Pharmacy (Gbagada)", "0803 633 6275", "7 Adekunle Osomo Street, Soluyi, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Pinco Pharmacy & Store (Gbagada)", "0802 311 7334", "28 Oke Street, Pedro, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Pius & Gina Pharmacy (Gbagada)", "No phone", "25 Diya Street, beside Fidelity Bank, Ifako Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Sabest Pharmacy", "0806 619 8166", "19 Church Street, Opp. Gbagada General Hospital", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Setz Pharmacy", "0803 331 7477", "1A Lanne Awolokun Street, Gbagada Phase 2", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Setz Pharmacy (Gbagada)", "0803 778 4608", "18 Ashimowu Street, Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("St. David's Pharmacy", "No phone", "Gbagada", "Independent Retailer", "Lagos", "Gbagada"),
    VerifiedPharmacy("Massey Vickers Pharmacy", "0803 325 3463", "117 Idimu Road, Abule Odu Bus stop", "Independent Retailer", "Lagos", "Idimu"),
    VerifiedPharmacy("Mekon Pharmacy", "No phone", "263 Ikotun-Idimu Road, Calvary Bus stop, Idimu", "Independent Retailer", "Lagos", "Idimu"),
    VerifiedPharmacy("Chivic Pharmacy", "+234 806 302 2117", "45 Nnamdi Azikiwe Street", "Independent Retailer", "Ogun", "Idumota"),
    VerifiedPharmacy("New Divine Pharmacy", "+234 803 475 1885", "12 Docemo Street", "Independent Retailer", "Ogun", "Idumota"),
    VerifiedPharmacy("Bolutife Pharmacy", "0803 716 7414", "60 Amusa Idowu Street, Ijegun", "Independent Retailer", "Lagos", "Ijegun"),
    VerifiedPharmacy("City of Glory Pharmacy", "0806 563 7705", "8 Araromi Junction, Ijegemo Road, Ijegun", "Independent Retailer", "Lagos", "Ijegun"),
    VerifiedPharmacy("Lighthouse Pharmacy", "No phone", "84 Agbado Road, Toyin Bus stop, Iju Ishaga", "Independent Retailer", "Lagos", "Iju-Ishaga"),
    VerifiedPharmacy("All Drug Pharmacy", "+234 803 307 0681", "72 Mobolaji Bank Anthony Way, Opebi", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("All Drugs Pharma LTD.", "+234 905 437 9892", "77B Mobolaji Bank Anthony Way", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Alpha Pharmacy & Stores Adeniyi Jones", "+234 906 000 6241", "GFL, 33 Adeniyi Jones", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Alpha Pharmacy & Stores Ltd", "01-2704374, 0906 000 6241, 0906 244 0935", "33 Adeniyi Jones Avenue", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Asset Pharmacy", "0903 455 3795", "1 Bethel Plaza, Olugbesan Close, Off Adegbeyemi Street, Allen Avenue", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Astute-Care Pharmacy", "0805 199 9704, 0807 611 5319, 0816 174 2232", "9 Alhaji Kofoworola Crescent, Off Obafemi Awolowo Way", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Atob Pharmacy", "No phone", "1 Toyin Street", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Bengerty Pharmacy & Stores Ltd", "0815 404 7090, 0916 641 2957", "3 Kudirat Abiola Way, Olusosun Bus Stop, Oregun", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Binklor Pharmacy & Stores", "0808 925 2624", "25 Afariogun Street, Off Awolowo Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Bolar Pharmaceuticals", "0705 481 7887, 0803 410 5614, 0813 328 9839", "5 Talabi Street, Off Adeniyi Jones Ave", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Boluke Pharmacy", "+234 803 322 3828, +234 903 361 8693, 0803 322 3828, 0812 800 0007", "134 Obafemi Awolowo Way", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Cantol Pharmacy & Stores", "01 493 2556", "56 Opebi Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Capstone Pharmacy & Stores", "0802 343 5779", "163 Akilo Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Caremax Pharmacy", "0802 321 0294", "2 Balogun Street, Off Obafemi Awolowo Way, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Cheltok Pharmacy", "No phone", "14 Allen Avenue", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Chemo Pharma Laboratory Limited", "0809 444 4275", "10 Olanrewaju Street, Oregun, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Chez Pharmacy", "+234 1 2630997", "70 Mobolaji Bank Anthony Way", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Chris-Ejik Pharmaceuticals", "+234 815 089 2289 / +234 906 600 0006", "No 3 Eje Ore-Imlavan Street, Off Oregun Road, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Divine Favour Chemist", "0803 229 4992", "9 Atinke Olabanji Street", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Drugstoc E-Hub Nig Ltd", "0703 787 1214", "3 Billings Way, Oregun, Ikeja", "Independent Wholesaler", "Lagos", "Ikeja"),
    VerifiedPharmacy("Elpha Pharmacy", "0817 004 2399", "64 Allen Avenue", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Fasid Pharmacy", "No phone", "Osunsina House, No 1 Ogunnusi Road, Omole Bus-stop, Agidingbi, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Forlab Pharmacy", "No phone", "8 Ola-Ayindestreet, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Franna Pharmacy", "0802 675 9174", "7 Opebi Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("GNC Livewell", "0815 577 8882", "1B Opebi Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("HealthPlus Pharmacy - Allen Avenue", "+234 707 455 7529, 0708 404 2498, 0809 589 8328", "Centage Plaza, 14 Allen Ave", "HealthPlus Chain Node", "Lagos", "Ikeja"),
    VerifiedPharmacy("HealthPlus Pharmacy - Ikeja City Mall", "+234 809 589 7922", "Shop L29, Ikeja City Mall", "HealthPlus Chain Node", "Lagos", "Ikeja"),
    VerifiedPharmacy("Juli Pharmacy", "+234 707 576 2933", "19 Kodesoh Street", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Lifepleni Pharmacy", "0810 959 1659", "23 Toyin Street, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Lilac Pharmacy", "+234 803 308 1103", "12 Ladipo Kuku Street, Off Allen Avenue", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("May & Baker Nigerian Plc Pharmacy Division", "01-3426886, 0811 368 1447, 0906 437 3040", "3/5 Sapara Street, Industrial Estate", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("MedPlus Pharmacy - MMIA", "+234 915 259 2974", "Murtala Mohammed International Airport", "Medplus Chain Node", "Lagos", "Ikeja"),
    VerifiedPharmacy("Mediheirs Pharmacy & Stores", "0809 515 2314", "11 Olaide Tomori Street", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Medplus - Opebi", "+234 908 204 2960", "61 Opebi Road", "Medplus Chain Node", "Lagos", "Ikeja"),
    VerifiedPharmacy("Medville Pharmacy", "01 497 2615, 0802 368 9185", "72 Allen Avenue", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("NETT Pharmacy Ltd", "+234 1 295 5051, 01-2955051, 01-7741255, 0807 453 5824", "33 Opebi Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("New Heights Pharmaceuticals Ltd", "0803 320 5868", "Suite BA28, 350/360 Ikorodu Road, Maryland", "Independent Wholesaler", "Lagos", "Ikeja"),
    VerifiedPharmacy("Pharmarket Pharmacy", "+234 705 051 3932", "2 Oyetubo St, Off Obafemi Awolowo Way", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Phiebiex Pharmacy", "+234 803 331 4703", "Oregun-Opebi Link Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Pius & Gina Pharmacy (EKO)", "No phone", "31C Mobolaji Bank Anthony Way, beside EKO Hospital, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Pius & Gina Pharmacy (MBW)", "No phone", "21 Mobolaji Bank Anthony Way, adjacent Ikeja Cantonment, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Reals Pharmaceuticals", "0809 142 5157", "Plot 1, Alhaji Dosumu Street, Alausa", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("SKT Healthcare Pharmaceuticals", "0703 637 0444, 0909 778 9655", "23 Ogunlowo Street, Off Awolowo Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Supplementsfield", "0805 125 9983, 0814 693 2782", "21 Obafemi Awolowo Way", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Tiptop Nigeria Limited", "0703 009 4731", "63 Oduduwa Crescent, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("TrooPharm (Ikeja)", "0901 190 0232", "6 Makinde Street, Off Awolowo Way, Testing Ground Bus Stop, Alausa, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Vitabiotics Nig. Ltd", "+234 803 408 7139 / +234 805 135 1410", "35 Mobolaji Johnson Avenue, Oregun Industrial Estate, Ikeja", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Wina Pharmacy", "No phone", "5/9 Oregun Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Windy Pharmacy", "No phone", "146 Obafemi Awolowo Way", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Winner Pharmacy & Chemist Industries", "No phone", "41 Oregun Road", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("Womisan Pharmacy", "+234 813 970 3311", "23 Oladosu Street, Off Olowu/Toyin Street", "Independent Retailer", "Lagos", "Ikeja"),
    VerifiedPharmacy("My-Medicines.com", "+234 808 275 1466", "12B Stella Solanke Street, International Airport Road, Ajao Estate", "Independent Retailer", "Lagos", "Ikeja Axis"),
    VerifiedPharmacy("Health Plus - Isaac John (Adebola Shopping Mall)", "+234 1 497 0404", "Unit 10, Adebola Shopping Mall, 53 Isaac John Street", "Independent Retailer", "Lagos", "Ikeja GRA"),
    VerifiedPharmacy("Medplus Pharmacy - Ikeja GRA", "+234 915 498 0431", "Ntel Store, 1 Sobo Arobiodu Street", "Medplus Chain Node", "Lagos", "Ikeja GRA"),
    VerifiedPharmacy("Medplus Pharmacy - Isaac John", "+234 915 049 3174", "29 Isaac John Street", "Medplus Chain Node", "Lagos", "Ikeja GRA"),
    VerifiedPharmacy("St. David's Pharmacy", "+234 703 294 6611", "14 Isaac John Street", "Independent Retailer", "Lagos", "Ikeja GRA"),
    VerifiedPharmacy("Neimeth International Pharmaceuticals", "+234 1 899 7402", "1 Henry Carr Street", "Independent Retailer", "Lagos", "Ikeja Industrial Estate"),
    VerifiedPharmacy("2Arms Pharmaceuticals", "0706 493 8010", "6 Agura, Gberighe Road, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Bjon & Tjon Pharmacy", "0818 873 3508", "Shop 23 POWA Shopping Complex, Sabo, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Charisland Pharmacy", "0802 851 6843", "47 Ijede Road, Omitoro, Ijede, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Constanstar Pharmacy", "0706 443 7405", "1 Rabaka Street, Owode, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("De-Lawrex Pharmacy", "0807 875 2897", "50 Obafemi Awolowo Way, Igbogbo, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Delkem Pharmacy", "0803 935 9078", "1 Oduyero Street, Odonguyan, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Drugsporte Pharmacy", "0703 943 9403", "1 Alegha Street, Off Owode Ibeshe Road, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Drugstore.ng", "0907 977 2482", "4/6 Ikorodu-Epe Rd, opposite Sabo Market, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Drugstore.ng Ikorodu", "0907 977 2482", "4/6 Ikorodu-Epe Road, opposite Sabo Market, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Ejide Pharmacy", "0802 306 3705", "1 Obafemi Taiwo, Off Igbogbo Road, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Empathy Pharmacy", "0806 453 7095", "Agura-Gberigbe, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Fizanac Pharmacy", "0812 901 8448", "86 Bayeku Road, Igbogbo, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Giottos Pharmacy (Agric)", "0806 904 5133", "155 Lagos Road, Agric Bus stop, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Giottos Pharmacy (Irawo)", "0808 939 8861", "Shop 1-3 Success Plaza, Irawo, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Good Care Pharmacy", "0806 080 0062", "111 Ishawo Road, Agric Bus stop, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Govatec Pharmacy", "No phone", "Isawo Road, RSA Bus Stop, Abule Cole, Agric, Owutu, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Goxatek Pharmacy", "0708 463 7410", "16 Gberighe Road, Off Ijede Road, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Hugies Pharmacy Ltd", "0815 391 1538", "39 Bola Tinubu Road, Igbogbo, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Iosba Pharmacy", "0909 826 5715", "26 Odegate Street, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("J & S Gold Pharmacy", "No phone", "21 Shagamu Road, Ikorodu / 6 Isele Street, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("J-Goal Pharmacy", "No phone", "23 Ayodele Ayeni Street, Eyita, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Ladamos Pharmacy (Ikorodu)", "0802 319 0162", "38 Ladega Street, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Lifegate Pharmacy", "0803 389 2682", "10 Etunrennen Road, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Lugz Pharmacy", "0809 395 5360 / 0806 312 1270", "58 Lagos Road, Opp. UBA, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Makinga Pharmacy (Ikorodu)", "0803 628 0477 / 0706 704 6404", "4 Alhaja Alagogo Street, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Mapic Pharmacy", "0805 601 8800", "73 Ireshe Street", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Marson Pharmacy", "0802 971 7376", "9 Ishawo Road, Agric Bus stop, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Med Arena Pharmacy", "0802 118 0855", "Agbede, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Paupix Pharmacy", "No phone", "16 Alison Street, Ojubode Bus stop, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Prinogold Pharmacy", "0809 680 1464", "1 Adeola Street, Off Fela Ahmed, Agric Bus stop, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Setz Pharmacy (Ikorodu)", "0909 826 5715", "139 Ijede Road, Off St. Raphael Catholic Hospital, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Steady Care Pharmacy", "0803 328 8827", "Tipper Garage, Offin/Oreta Road, Igbogbo, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Sybarmedics Pharmacy", "No phone", "Agbede Olorogbo Junction, Off Isawo Road, Agric, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("T & K Pharmacy", "0803 378 7143", "Agbaje Bus Stop, Enwuen Road, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("T.T. Robinson Pharmacy", "0806 080 0062", "79 Odonla Road, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Telson Pharmacy", "0806 904 5133", "159 Ishawo Road, Agric Bus stop, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Urocheck Pharmacy", "0813 021 0092", "TJ Bus stop, Agbede, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Wecare Pharmacy", "0814 891 2955", "Prince of Peace Shopping Plaza, 300 Ikorodu-Shagamu Road, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("Winlot Pharmacy", "0804 004 6182", "Ijede Road, Eleshin, Ikorodu", "Independent Retailer", "Lagos", "Ikorodu"),
    VerifiedPharmacy("ExC Pharmacy Ikota, Lekki", "+234 707 838 9227", "6B Francis Ojei Street, Chevron Alternative Road", "Independent Retailer", "Ogun", "Ikota"),
    VerifiedPharmacy("Medplus Pharmacy - Ikota", "0905 388 7571", "Lekki-Epe Expressway, opposite Mega Chicken", "Medplus Chain Node", "Ogun", "Ikota"),
    VerifiedPharmacy("Health Maps Pharmacy", "No phone", "1 Adekunjo Street, opposite Synagogue Church, Ikotun", "Independent Retailer", "Lagos", "Ikotun"),
    VerifiedPharmacy("Jaybee Pharmacy", "No phone", "65 Idimu Road, College Bus stop, Ikotun", "Independent Retailer", "Lagos", "Ikotun"),
    VerifiedPharmacy("PeaceWay Pharmacy", "0808 567 5123", "3 Igando Road, Ikotun", "Independent Retailer", "Lagos", "Ikotun"),
    VerifiedPharmacy("Prinsa Healthcare", "No phone", "6 Ayeni Street, Off Layi Haruna Street, Governor's Road, Ikotun", "Independent Retailer", "Lagos", "Ikotun"),
    VerifiedPharmacy("Riyi Pharmacy", "No phone", "35 El-Bethel Church Street, Lawal Bus stop, Governor's Road, Ikotun", "Independent Retailer", "Lagos", "Ikotun"),
    VerifiedPharmacy("Afripharm Multiscience Co. Ltd", "No phone", "15 Kingsway Road, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Carlisle Pharm. & Chem. Co. Ltd", "No phone", "19 Ribadu Road, South West, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Chemart Pharmacy", "0818 205 9355", "2 Olawale Dawodu Street (Former Webb Road)", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Chemart Pharmacy - Ikoyi", "0818 205 9355", "7/12 Rumens Road, Off Alfred Rewane Road, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Chyzob Pharmacy Limited", "0802 835 6250, 0813 104 8008, 0817 000 1325", "168 Awoniyi Road", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Commark Pharm. Ventures Ltd", "No phone", "Shop 60, LSDPC, Corporation Drive, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Curemed Pharmacy Ltd", "No phone", "31 Keffi Street, By Norman William Street, S/W Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Danisam Pharm. Ltd", "No phone", "11 Nojeem Maiyegun Road, Obalende, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Elbe Pharm. Nig. Ltd", "No phone", "4 Akanbi Danmola Street, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Executive Pharm. Chemists", "No phone", "B2 Falomo Shopping Centre, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Hess Pharmacy", "No phone", "130 Awolowo Road, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Lasucre Pharmacy & Store", "+234 915 323 6728", "30 King George Road", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Medplus Pharmacy- Ikoyi", "+234 915 259 2953", "168 Awoniyi Road", "Medplus Chain Node", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Menbon Pharmacy", "No phone", "37C Raymond Njoku Street, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Nina-Adonai Pharmacy", "No phone", "Shop 10 Ikeja Way, Dolphin Estate, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Panvij Biotec Nig. LTD.", "No phone", "15 Biaduo Street, off Keffi Street, S/W Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("Pearle Pharmacy", "No phone", "32 Ajeniya Street, off Obalende, Ikoyi", "Independent Retailer", "Lagos", "Ikoyi"),
    VerifiedPharmacy("All Gates Pharmacy", "0803 549 5128", "Shop 20/21 Jonwo Plaza, Ilupeju", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Assure Pharmacy", "0803 717 3626", "7 Adeshida Street, Ilupeju", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Clarion Medicals Ltd", "0809 014 9999, 0816 644 4393", "23 Afolabi Lesi Street, Off Town Planning Way", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Greenlife Pharmaceuticals Ltd", "0704 618 3350, 0704 618 3353", "2 Bank Lane, Town Planning", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Jathom Pharmacy", "0814 124 4164", "78 Shyllon Street, Palmgrove, Ilupeju", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Lifestores Pharmacy", "0905 909 1484, 0909 030 7612", "46 Coker Road", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Orange Drugs Limited", "0702 799 8947, 0702 799 8993, 0709 814 7939", "66/68 Town Planning Way", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Superdrug Integrated Pharmacy", "0803 077 6767, 0908 026 7284", "30 Ilupeju Bypass, Heyden Filling Station", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Theodor Pharmacy", "0706 663 0119", "13 Association Avenue", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Toogun Pharmacy", "0818 000 1995", "21 Esther Oshiyemi Street, Ilupeju", "Independent Retailer", "Lagos", "Ilupeju"),
    VerifiedPharmacy("Abincare Pharmacy", "0818 337 8666", "2 Ikola Road, Off Command Road, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Ajib Pharmacy", "0803 225 4426", "12A Command Road, Command", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Bonamour Pharmacy", "0809 512 7000", "23 Baruwa Road, Baruwa, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("De-Omega Healthcare", "0803 596 3349", "7 Church Street, Akinogun Bus stop, Shagari Estate, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Joekem Pharmacy", "No phone", "234 Ipaja-Ayobo Road, Opebi Bus stop, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Joekem Pharmacy (Ipaja)", "0803 447 2707", "Church Bus stop, Ipaja Road, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Joelad Pharmacy", "No phone", "203 Abule-Egun Bus stop, Ipaja Road, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Lanbib Pharmacy", "No phone", "Block 331, Flat 1, Abasan Estate, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Mascot Pharmacy", "No phone", "1 Monilari Close, Shagari Estate, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Medgreens Pharmacy", "0708 230 0349", "1 Command Road, Command, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Olive Manex Pharmacy", "0802 220 4312 / 0703 805 4422", "1 Kareem Bankole Street, Off Candos Road, Baruwa", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Olivemanex Pharmacy", "No phone", "1 Karim Bankole Street, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("Ufot-MfonSe Pharmacy", "No phone", "142 Ayobo Road, Ipaja", "Independent Retailer", "Lagos", "Ipaja"),
    VerifiedPharmacy("A F Uchenna Pharmacy", "0802 545 0757", "6 Aderinto Street, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("A.F. Uchenna Pharmacy Ltd", "0802 545 0757", "6 Aderinto Street, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Akugbe Pharmacy & Stores Ltd", "No phone", "2 Olufemi Kolawole Street, Okota, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Bandar Pharm. Ltd", "No phone", "1A Coker Road, Ejigbo, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Beyiscon Nig. Ltd", "No phone", "129 Okota Road, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Biggs Pharm. Ltd", "No phone", "9 Lateef Salami Street, Ajao Estate, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("CHI Pharmaceuticals", "+234 1 452 0629 / 0803 715 0506", "14 Chivita Avenue, Ajao Estate, Isolo, Lagos", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Chriswill Pharmaceutical Co. Ltd", "No phone", "2 Muyili Oshode Street, Ejigbo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Chymasen Pharmacy Nig. Ltd", "No phone", "2 Taiwo Street, Okota, Ago Palace Way, Okota", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("De Japhson Pharmacy Ltd", "No phone", "40/42 Ago Palace Way, Okota, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("E'Dote Pharmaceutical Nig. Ltd", "No phone", "34 Okeho Street, Ire Akari Estate, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Ezeyisi & Sons Pharmacy Ltd", "No phone", "27B Okota Palace Way, Okota", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("James Adile Pharm. Nig Ltd", "No phone", "304 Mushin Road, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Kings Chemist & Cosmetics", "No phone", "54 Okota Palace Way, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Lanyard Pharmacy & Stores Ltd", "No phone", "63 Palace Way, Okota, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Marvel Pharm. Co. Ltd", "No phone", "61/63 Falana Street, Ejigbo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Medmark Limited (Ajao)", "No phone", "29 M.M. Airport Road, Ajao Estate, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Medreich Nig. LTD.", "No phone", "11 Enoma Street, off Ago-Palace Way, Okota", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Nesco Pharm. Co. LTD.", "No phone", "Shop 3/4 L.C.H.E. Oke-Afa, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Palm Pharmacy", "No phone", "22 Akinbaye Street, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Prime Pharm. LTD.", "No phone", "7 Ire Akari Estate Road, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Prodrug Pharmacy", "0805 612 5213", "7B Asa Afariogun Street, Ajao Estate, Off International Airport Road", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Shepherd Food & Pharm. Ind. Ltd", "No phone", "2 Dorishamu Close, Okota, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Spring Forth Pharmacy", "0802 306 0747", "34 Alhaja Adenekan Street, Oke Afa, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Stella-Charles Pharm & Stores Ltd", "No phone", "45A Okota Road, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Torrent Pharmacy", "0806 025 7252", "26 Goloba Street, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Turmeric Pharmacy", "0818 298 9540", "41 Ire Akari Estate Road", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Welnex Pharmacy", "0703 211 2589", "7 Isolo Road, Jakande Estate, Isolo", "Independent Retailer", "Lagos", "Isolo"),
    VerifiedPharmacy("Pill Box Pharmacy", "0803 377 2943", "4 Olumo Street, Onike", "Independent Retailer", "Lagos", "Iwaya"),
    VerifiedPharmacy("Egomore Pharmacy", "No phone", "1 Oyiba Drive, Iba, Iyana Iba", "Independent Retailer", "Lagos", "Iyana Iba"),
    VerifiedPharmacy("St. Jude Pharmacy", "No phone", "81 Ojo-Igbede Road, Iba, Iyana Iba", "Independent Retailer", "Lagos", "Iyana Iba"),
    VerifiedPharmacy("Domec United Pharmacy", "No phone", "Iyana Ipaja Garage, Iyana Ipaja", "Independent Retailer", "Lagos", "Iyana Ipaja"),
    VerifiedPharmacy("Medstar Pharmacy", "0812 216 3556", "1A Hussey Road", "Independent Retailer", "Lagos", "Jibowu"),
    VerifiedPharmacy("Teemcare Pharmacy", "0809 813 7516", "34/36 Ikorodu Road", "Independent Retailer", "Lagos", "Jibowu"),
    VerifiedPharmacy("Amexco Pharmacy", "0813 440 1031", "1 Ikosi Road, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Chizzy Pharmacy", "0813 827 7916", "18 Ikosi Road, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Divine Chemist (Ketu 2)", "0814 167 4678", "16 Adebayo Street, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Divine Chemist (Ketu)", "0816 055 1714", "2 Owodunni Street, Ikosi, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Gally Pharmacy", "No phone", "98 Demurin Street, Alapere, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Gocrest Pharmacy", "No phone", "26 Agidi Road, Opposite CAC Church, Iyakan Bus-stop, Alapere, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Goodcare Pharmacy", "0806 080 0062", "500 Ikorodu Road, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Herbinco Pharmacy (Ketu)", "0807 407 9805", "28 Demurin Street, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Ifex Pharmacy", "0708 488 0430", "1 Okunowo Street, Ikosi Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Kaften Flash Pharmacy", "No phone", "37 Kazeem Street, Alapere, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Makinga Pharmacy (Ketu)", "0706 124 4076", "3 Dele Okuwa Street, Ikosi, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Patvics Pharmacy", "0818 566 6323", "603 Ikorodu Road, Mile 12, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Sera Pharmacy", "0803 726 4168 / 0808 624 9926", "2A Doyin Omololu Road, Off Demurin Street, Ketu-Alapere", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("St. Peters & Paul's Pharmacy", "0816 606 7735", "15 Elejibu Street, Ketu", "Independent Retailer", "Lagos", "Ketu"),
    VerifiedPharmacy("Afonchies Pharmaceuticals Limited", "0705 449 2940", "Shop 6, Ganiyi Daudu Street, Abraham Adesanya Estate, Lekki-Epe Expressway", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Anne Pharmacy Store", "0805 805 2314", "35 Post Office Road, Onipanu", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Arowolo Pharmacy", "0802 136 3342, 0802 911 0894", "7 Isheri Road, Idimu", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Beneze Pharmacy Limited", "0706 703 5990, 0803 715 5854", "4 Demurin Street, Ketu", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Dana Drugs Limited", "01 773 0054, 0802 776 7777", "KM 4 Apapa-Oshodi Expressway, Ijesha", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Drugstore.ng (Online)", "0907 977 2482", "Lagos (Delivery statewide)", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Enavec Pharmacy", "0706 835 7391", "26, 4th Avenue, Festac Town", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Frank-Chuks Pharmacy Ltd", "0706 921 2733", "2A Oseni Street, Iyana-Iba", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("HealthServe Pharmacy", "No phone", "4 Ladipo Adeyemi Street, Anthony Village", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Healthy Child Pharmacy", "0808 035 6154 / 0818 780 9366", "462, 5th Avenue, Gowon Estate, Egbeda", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Help Pharmacy", "No phone", "145/147 Ago Palace Way, Okota", "Independent Retailer", "Lagos", "Lagos"),
    VerifiedPharmacy("Healthy Pulse Pharmacy Ltd", "No phone", "346 Herbert Macaulay Way", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Kasville Pharmacy", "0810 454 2510", "22 Montgomery Road", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Lexicon Pharmacy & Supermarket", "0702 938 9149", "6 Iwaya Road, Onike, Yaba", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Livewell Pharmacy", "No phone", "Yaba", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Medlounge Pharmacy", "No phone", "285 Herbert Macaulay Way, Yaba", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Metromeds Pharmacy Limited", "0817 283 6273", "6 Queens Street Casino, Off Herbert Macaulay Way", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Okolowhite Pharmacy", "0803 321 7034", "41A Commercial Avenue, Sabo", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Omowunmi Titilayo Pharmacy", "0802 594 3727", "371 Borno Way, Alagomeji", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Pharma Solutions", "0809 111 1608, 0809 111 1908, 0810 493 1060", "25 Montgomery Road, Off Herbert Macaulay Way", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Pharmasolution Pharmacy", "0703 037 4411", "28 Commercial Avenue, Yaba", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Pill Box Pharmacy (Yaba)", "0706 119 0149", "5 Olumo Street, Onike, Yaba", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Remey Pharmacy", "0803 325 7114", "Tanimo Street, Off Ikorodu Road, Fadeyi Bus stop", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Reneca Pharmacy", "0809 759 2042", "17 Mosuro Street, Abule Oja, Yaba", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Robson Pharmacy", "No phone", "Sanyaolu Street, Akoka", "Independent Retailer", "Lagos", "Yaba"),
    VerifiedPharmacy("Sheba Pharmacy", "0704 949 0853", "32B Yaba Tech Staff Quarters, Aggrey Road, GRA", "Independent Retailer", "Lagos", "Yaba"),
)
